services:
  flask-web:
    image: keizo410/backend-flask-web:latest
    ports:
      - "${FLASK_RUN_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "${RABBITMQ_UI_PORT}:15672"  # RabbitMQ Management UI
      - "${AMQP_PORT}:5672"    # AMQP port
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery --app celery_tasks.tasks.celery worker --loglevel=info --logfile=celery_tasks/logs/celery.log
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env 
    environment:
      - PYTHONPATH=/app
      - FLASK_DEBUG=1
      - APP_SETTINGS=celery_tasks.config.DevelopmentConfig
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - flask-web
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
