version: '3'
services:
  flask-web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - ngrok
    networks:
      - app-network

  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_PORT=flask-web:${FLASK_RUN_PORT}
    ports:
      - "4040:4040"
    networks:
      - app-network
  
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: