services:
  flask-web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${FLASK_RUN_PORT}:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network 

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # AMQP port
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery --app celery_tasks.tasks.celery worker --loglevel=info --logfile=celery_tasks/logs/celery.log
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - FLASK_DEBUG=1
      - APP_SETTINGS=celery_tasks.config.DevelopmentConfig
      - CELERY_BROKER_URL=amqp://guest@rabbitmq//
    depends_on:
      - flask-web
      - rabbitmq
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  pgdata: