name: Running unit test suits
on: push 
jobs: 
  automated-testing-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"

      - name: Set up environment variables for Docker container
        run: |
          echo "FLASK_APP=server.py" >> $GITHUB_ENV
          echo "FLASK_ENV=development" >> $GITHUB_ENV
          echo "FLASK_RUN_PORT=8000" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "DATABASE=${{ secrets.DATABASE }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.USER }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          echo "NGROK_AUTHTOKEN=${{ secrets.NGROK_AUTHTOKEN }}" >> $GITHUB_ENV

      - name: Run Docker Compose and Tests
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./backend/docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "flask-web"
          test-command: "pytest tests/"

      # Optionally, shut down and clean up the container
      - name: Shut down Docker containers
        run: docker-compose down --volumes --remove-orphans
