name: Running unit test suits
on: push 
jobs: 
  automated-testing-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"

      - name: Create `.env` file from environment variables
        run: |
          echo "FLASK_APP=$FLASK_APP" >> .env
          echo "FLASK_ENV=$FLASK_ENV" >> .env
          echo "FLASK_RUN_PORT=$FLASK_RUN_PORT" >> .env
          echo "API_KEY=$API_KEY" >> .env
          echo "BASE_YT_URL=$BASE_YT_URL" >> .env
          echo "API_URL=$API_URL" >> .env
          echo "HUB_URL=$HUB_URL" >> .env
          echo "BASE_TOPIC_URL=$BASE_TOPIC_URL" >> .env
          echo "TOPIC_URL=$TOPIC_URL" >> .env
          echo "NGROK_AUTHTOKEN=$NGROK_AUTHTOKEN" >> .env
          echo "APP_PASSWORD=$APP_PASSWORD" >> .env
          echo "SENDER_EMAIL=$SENDER_EMAIL" >> .env
          echo "RECEIVER_EMAIL=$RECEIVER_EMAIL" >> .env
          echo "DATABASE=$DATABASE" >> .env
          echo "USER=$USER" >> .env
          echo "PASSWORD=$PASSWORD" >> .env
          echo "HOST=$HOST" >> .env
          echo "PORT=$PORT" >> .env

      - name: Run Docker Compose and Tests
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./backend/docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "flask-web"
          test-command: "pytest tests/"

      # Optionally, shut down and clean up the container
      - name: Shut down Docker containers
        run: docker-compose down --volumes --remove-orphans
